use clap::Parser;
use std::fmt;

#[derive(Parser, Clone)]
#[command(
    name = "cc_matrix_channel",
    about = "Matrix channel bridge for Claude Code"
)]
pub struct Config {
    /// Matrix homeserver URL (e.g. https://matrix.example.com)
    #[arg(long, env = "MATRIX_HOMESERVER_URL")]
    pub homeserver_url: String,

    /// Matrix password for initial login — use MATRIX_PASSWORD env var.
    /// Required for first-run E2EE setup. Subsequent runs use saved session.
    #[arg(long, env = "MATRIX_PASSWORD", hide = true)]
    pub password: Option<String>,

    /// Matrix access token (fallback) — use MATRIX_ACCESS_TOKEN env var.
    /// Optional if MATRIX_PASSWORD is provided (token generated by login).
    #[arg(long, env = "MATRIX_ACCESS_TOKEN", hide = true)]
    pub access_token: Option<String>,

    /// Matrix user ID (e.g. @bot:example.com). Required.
    #[arg(long, env = "MATRIX_USER_ID")]
    pub user_id: String,

    /// Matrix device ID hint. Auto-generated on first login if omitted.
    #[arg(long, env = "MATRIX_DEVICE_ID")]
    pub device_id: Option<String>,

    /// Path for SQLite store (E2EE keys + sync state)
    #[arg(long, env = "MATRIX_STORE_PATH", default_value = "./data/matrix_store")]
    pub store_path: String,

    /// Optional passphrase to encrypt the SQLite E2EE store on disk — use MATRIX_STORE_PASSPHRASE env var
    #[arg(long, env = "MATRIX_STORE_PASSPHRASE", hide = true)]
    pub store_passphrase: Option<String>,
}

impl fmt::Debug for Config {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Config")
            .field("homeserver_url", &self.homeserver_url)
            .field("password", &self.password.as_ref().map(|_| "[REDACTED]"))
            .field(
                "access_token",
                &self.access_token.as_ref().map(|_| "[REDACTED]"),
            )
            .field("user_id", &self.user_id)
            .field("device_id", &self.device_id)
            .field("store_path", &self.store_path)
            .field(
                "store_passphrase",
                &self.store_passphrase.as_ref().map(|_| "[REDACTED]"),
            )
            .finish()
    }
}

impl Config {
    /// Extract the localpart from the user_id for login_username.
    /// e.g. "@claude:example.com" → "claude"
    pub fn user_localpart(&self) -> &str {
        let uid = self.user_id.trim();
        let uid = uid.strip_prefix('@').unwrap_or(uid);
        uid.split(':').next().unwrap_or(uid)
    }
}
